version: "2"
run:
  build-tags:
    - e2e
    - probe
    - preupgrade
    - postupgrade
    - postdowngrade
linters:
  enable:
    - asciicheck
    - gosec
    - prealloc
    - unconvert
    - unparam
  disable:
    - errcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
          - unparam
        path: test
    paths:
      - third_party$
      - builtin$
      - examples$
      - pkg/client
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - pkg/client
