run:
  timeout: 10m

  build-tags:
    - e2e
    - probe
    - preupgrade
    - postupgrade
    - postdowngrade

linters:
  enable:
    - asciicheck
    - gosec
    - prealloc
    - unconvert
    - unparam
  disable:
    - errcheck

issues:
  exclude-dirs:
    - pkg/client
  exclude-rules:
    - path: test # Excludes /test, *_test.go etc.
      linters:
        - gosec
        - unparam
