/*
Copyright 2021 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "knative.dev/eventing/pkg/apis/sinks/v1alpha1"
	scheme "knative.dev/eventing/pkg/client/clientset/versioned/scheme"
)

// IntegrationSinksGetter has a method to return a IntegrationSinkInterface.
// A group's client should implement this interface.
type IntegrationSinksGetter interface {
	IntegrationSinks(namespace string) IntegrationSinkInterface
}

// IntegrationSinkInterface has methods to work with IntegrationSink resources.
type IntegrationSinkInterface interface {
	Create(ctx context.Context, integrationSink *v1alpha1.IntegrationSink, opts v1.CreateOptions) (*v1alpha1.IntegrationSink, error)
	Update(ctx context.Context, integrationSink *v1alpha1.IntegrationSink, opts v1.UpdateOptions) (*v1alpha1.IntegrationSink, error)
	UpdateStatus(ctx context.Context, integrationSink *v1alpha1.IntegrationSink, opts v1.UpdateOptions) (*v1alpha1.IntegrationSink, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IntegrationSink, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IntegrationSinkList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationSink, err error)
	IntegrationSinkExpansion
}

// integrationSinks implements IntegrationSinkInterface
type integrationSinks struct {
	client rest.Interface
	ns     string
}

// newIntegrationSinks returns a IntegrationSinks
func newIntegrationSinks(c *SinksV1alpha1Client, namespace string) *integrationSinks {
	return &integrationSinks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the integrationSink, and returns the corresponding integrationSink object, and an error if there is any.
func (c *integrationSinks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IntegrationSink, err error) {
	result = &v1alpha1.IntegrationSink{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("integrationsinks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IntegrationSinks that match those selectors.
func (c *integrationSinks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IntegrationSinkList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IntegrationSinkList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("integrationsinks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested integrationSinks.
func (c *integrationSinks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("integrationsinks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a integrationSink and creates it.  Returns the server's representation of the integrationSink, and an error, if there is any.
func (c *integrationSinks) Create(ctx context.Context, integrationSink *v1alpha1.IntegrationSink, opts v1.CreateOptions) (result *v1alpha1.IntegrationSink, err error) {
	result = &v1alpha1.IntegrationSink{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("integrationsinks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(integrationSink).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a integrationSink and updates it. Returns the server's representation of the integrationSink, and an error, if there is any.
func (c *integrationSinks) Update(ctx context.Context, integrationSink *v1alpha1.IntegrationSink, opts v1.UpdateOptions) (result *v1alpha1.IntegrationSink, err error) {
	result = &v1alpha1.IntegrationSink{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("integrationsinks").
		Name(integrationSink.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(integrationSink).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *integrationSinks) UpdateStatus(ctx context.Context, integrationSink *v1alpha1.IntegrationSink, opts v1.UpdateOptions) (result *v1alpha1.IntegrationSink, err error) {
	result = &v1alpha1.IntegrationSink{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("integrationsinks").
		Name(integrationSink.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(integrationSink).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the integrationSink and deletes it. Returns an error if one occurs.
func (c *integrationSinks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("integrationsinks").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *integrationSinks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("integrationsinks").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched integrationSink.
func (c *integrationSinks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationSink, err error) {
	result = &v1alpha1.IntegrationSink{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("integrationsinks").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
