apiVersion: channels.knative.dev/v1alpha1
kind: Bus
metadata:
  name: kafka
spec:
  parameters:
    subscription:
    - name: "initialOffset"
      description: "The initial offset to use when subscribing, either Oldest or Newest. Defaults to Newest."
      default: "Newest"
  provisioner:
    name: provisioner
    image: github.com/knative/eventing/pkg/buses/kafka/provisioner
    args: [
      "-logtostderr",
      "-stderrthreshold", "INFO",
    ]
    env: &env
    - name: KAFKA_BOOTSTRAP_SERVERS
      valueFrom:
        configMapKeyRef:
          name: kafka-bus-config
          key: KAFKA_BOOTSTRAP_SERVERS
  dispatcher:
    name: dispatcher
    image: github.com/knative/eventing/pkg/buses/kafka/dispatcher
    args: [
      "-logtostderr",
      "-stderrthreshold", "INFO",
    ]
    env: *env
