apiVersion: messaging.knative.dev/v1alpha1
kind: InMemoryChannel
metadata:
  name: imc
spec:
  # Channel delivery configuration
  delivery:
    retry: 5
    backoffPolicy: exponential
    backoffDelay: 3s
  subscribable: # populated by Subscription
    subscribers:
    - subscriberURI: mysub.default.svc.cluster.local
      delivery:
        deadLetterSinkURI: mydls.default.svc.cluster.local

