apiVersion: messaging.knative.dev/v1beta1
kind: InMemoryChannel
metadata:
  name: imc
spec:
  # Channel delivery configuration
  delivery:
    retry: 5
    backoffPolicy: exponential
    backoffDelay: 3s
  subscribers:
  - subscriberURI: mysub.default.svc.cluster.local
    delivery:
      deadLetterSinkURI: mydls.default.svc.cluster.local

