apiVersion: messaging.knative.dev/v1beta1
kind: InMemoryChannel
metadata:
  name: imc
spec:
  delivery:
    deadLetterSink:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: handle-error
    retry: 5
    backoffPolicy: exponential
    backoffDelay: 3s
  subscribers:
  - subscriberURI: mysub.default.svc.cluster.local

