# curl localhost:8080/default/job-sink -v -X POST -H "Content-Type: application/json"   -H "ce-specversion: 1.0" -H "ce-type: com.mycompany.myapp.myservice.myevent"   -H "ce-source: mysource3/myservice"   -H "ce-id: 2234-5678"   -H "ce-time: 2023-01-02T12:34:56.789Z"   -H "ce-subject: my-important-subject"   -H "ce-extensionattr1: value"   -H "ce-extensionattr2: 5"   -d '{"foo1": "bar1", "foo2": "bar2"}'

apiVersion: sinks.knative.dev/v1alpha1
kind: JobSink
metadata:
  name: job-sink-failure
spec:
  job:
    apiVersion: batch/v1
    kind: Job
    spec:
      completions: 12
      parallelism: 3
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              image: docker.io/library/bash:5
              command: [ "bash" ]        # example command simulating a bug which triggers the FailJob action
              args:
                - -c
                - echo "Hello world!" && sleep 5 && exit 42
      backoffLimit: 6
      podFailurePolicy:
        rules:
          - action: FailJob
            onExitCodes:
              containerName: main      # optional
              operator: In             # one of: In, NotIn
              values: [ 42 ]
          - action: Ignore             # one of: Ignore, FailJob, Count
            onPodConditions:
              - type: DisruptionTarget   # indicates Pod disruption
