/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/knative/eventing/pkg/apis/eventing/v1alpha1"
	scheme "github.com/knative/eventing/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterProvisionersGetter has a method to return a ClusterProvisionerInterface.
// A group's client should implement this interface.
type ClusterProvisionersGetter interface {
	ClusterProvisioners() ClusterProvisionerInterface
}

// ClusterProvisionerInterface has methods to work with ClusterProvisioner resources.
type ClusterProvisionerInterface interface {
	Create(*v1alpha1.ClusterProvisioner) (*v1alpha1.ClusterProvisioner, error)
	Update(*v1alpha1.ClusterProvisioner) (*v1alpha1.ClusterProvisioner, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ClusterProvisioner, error)
	List(opts v1.ListOptions) (*v1alpha1.ClusterProvisionerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterProvisioner, err error)
	ClusterProvisionerExpansion
}

// clusterProvisioners implements ClusterProvisionerInterface
type clusterProvisioners struct {
	client rest.Interface
}

// newClusterProvisioners returns a ClusterProvisioners
func newClusterProvisioners(c *EventingV1alpha1Client) *clusterProvisioners {
	return &clusterProvisioners{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterProvisioner, and returns the corresponding clusterProvisioner object, and an error if there is any.
func (c *clusterProvisioners) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterProvisioner, err error) {
	result = &v1alpha1.ClusterProvisioner{}
	err = c.client.Get().
		Resource("clusterprovisioners").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterProvisioners that match those selectors.
func (c *clusterProvisioners) List(opts v1.ListOptions) (result *v1alpha1.ClusterProvisionerList, err error) {
	result = &v1alpha1.ClusterProvisionerList{}
	err = c.client.Get().
		Resource("clusterprovisioners").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterProvisioners.
func (c *clusterProvisioners) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("clusterprovisioners").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a clusterProvisioner and creates it.  Returns the server's representation of the clusterProvisioner, and an error, if there is any.
func (c *clusterProvisioners) Create(clusterProvisioner *v1alpha1.ClusterProvisioner) (result *v1alpha1.ClusterProvisioner, err error) {
	result = &v1alpha1.ClusterProvisioner{}
	err = c.client.Post().
		Resource("clusterprovisioners").
		Body(clusterProvisioner).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterProvisioner and updates it. Returns the server's representation of the clusterProvisioner, and an error, if there is any.
func (c *clusterProvisioners) Update(clusterProvisioner *v1alpha1.ClusterProvisioner) (result *v1alpha1.ClusterProvisioner, err error) {
	result = &v1alpha1.ClusterProvisioner{}
	err = c.client.Put().
		Resource("clusterprovisioners").
		Name(clusterProvisioner.Name).
		Body(clusterProvisioner).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterProvisioner and deletes it. Returns an error if one occurs.
func (c *clusterProvisioners) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clusterprovisioners").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterProvisioners) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("clusterprovisioners").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterProvisioner.
func (c *clusterProvisioners) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterProvisioner, err error) {
	result = &v1alpha1.ClusterProvisioner{}
	err = c.client.Patch(pt).
		Resource("clusterprovisioners").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
