/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/knative/eventing/pkg/apis/eventing/v1alpha1"
	scheme "github.com/knative/eventing/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ProvisionerReferencesGetter has a method to return a ProvisionerReferenceInterface.
// A group's client should implement this interface.
type ProvisionerReferencesGetter interface {
	ProvisionerReferences(namespace string) ProvisionerReferenceInterface
}

// ProvisionerReferenceInterface has methods to work with ProvisionerReference resources.
type ProvisionerReferenceInterface interface {
	Create(*v1alpha1.ProvisionerReference) (*v1alpha1.ProvisionerReference, error)
	Update(*v1alpha1.ProvisionerReference) (*v1alpha1.ProvisionerReference, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ProvisionerReference, error)
	List(opts v1.ListOptions) (*v1alpha1.ProvisionerReferenceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ProvisionerReference, err error)
	ProvisionerReferenceExpansion
}

// provisionerReferences implements ProvisionerReferenceInterface
type provisionerReferences struct {
	client rest.Interface
	ns     string
}

// newProvisionerReferences returns a ProvisionerReferences
func newProvisionerReferences(c *EventingV1alpha1Client, namespace string) *provisionerReferences {
	return &provisionerReferences{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the provisionerReference, and returns the corresponding provisionerReference object, and an error if there is any.
func (c *provisionerReferences) Get(name string, options v1.GetOptions) (result *v1alpha1.ProvisionerReference, err error) {
	result = &v1alpha1.ProvisionerReference{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("provisionerreferences").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ProvisionerReferences that match those selectors.
func (c *provisionerReferences) List(opts v1.ListOptions) (result *v1alpha1.ProvisionerReferenceList, err error) {
	result = &v1alpha1.ProvisionerReferenceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("provisionerreferences").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested provisionerReferences.
func (c *provisionerReferences) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("provisionerreferences").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a provisionerReference and creates it.  Returns the server's representation of the provisionerReference, and an error, if there is any.
func (c *provisionerReferences) Create(provisionerReference *v1alpha1.ProvisionerReference) (result *v1alpha1.ProvisionerReference, err error) {
	result = &v1alpha1.ProvisionerReference{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("provisionerreferences").
		Body(provisionerReference).
		Do().
		Into(result)
	return
}

// Update takes the representation of a provisionerReference and updates it. Returns the server's representation of the provisionerReference, and an error, if there is any.
func (c *provisionerReferences) Update(provisionerReference *v1alpha1.ProvisionerReference) (result *v1alpha1.ProvisionerReference, err error) {
	result = &v1alpha1.ProvisionerReference{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("provisionerreferences").
		Name(provisionerReference.Name).
		Body(provisionerReference).
		Do().
		Into(result)
	return
}

// Delete takes name of the provisionerReference and deletes it. Returns an error if one occurs.
func (c *provisionerReferences) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("provisionerreferences").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *provisionerReferences) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("provisionerreferences").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched provisionerReference.
func (c *provisionerReferences) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ProvisionerReference, err error) {
	result = &v1alpha1.ProvisionerReference{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("provisionerreferences").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
