apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: brokers.eventing.knative.dev
spec:
  scope: Namespaced
  group: eventing.knative.dev
  version: v1alpha1
  names:
    kind: Broker
    plural: brokers
    singular: broker
