apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: subscriptions.eventing.knative.dev
spec:
  scope: Namespaced
  group: eventing.knative.dev
  version: v1alpha1
  names:
    kind: Subscription
    plural: subscriptions
    singular: subscription
