load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["register.go"],
    importpath = "github.com/elafros/eventing/pkg/apis/bind",
    visibility = ["//visibility:public"],
)
