apiVersion: channels.knative.dev/v1alpha1
kind: Channel
metadata:
  name: aloha
spec:
  bus: stub

---
apiVersion: channels.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: aloha2hello
spec:
  channel: aloha
  subscriber: hello-00001-service
