/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	channels_v1alpha1 "github.com/knative/eventing/pkg/apis/channels/v1alpha1"
	versioned "github.com/knative/eventing/pkg/client/clientset/versioned"
	internalinterfaces "github.com/knative/eventing/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/knative/eventing/pkg/client/listers/channels/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BusInformer provides access to a shared informer and lister for
// Buses.
type BusInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.BusLister
}

type busInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBusInformer constructs a new informer for Bus type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBusInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBusInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBusInformer constructs a new informer for Bus type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBusInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ChannelsV1alpha1().Buses(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ChannelsV1alpha1().Buses(namespace).Watch(options)
			},
		},
		&channels_v1alpha1.Bus{},
		resyncPeriod,
		indexers,
	)
}

func (f *busInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBusInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *busInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&channels_v1alpha1.Bus{}, f.defaultInformer)
}

func (f *busInformer) Lister() v1alpha1.BusLister {
	return v1alpha1.NewBusLister(f.Informer().GetIndexer())
}
