apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: pubsub
  namespace: default
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: gcp-pubsub
