# Copyright 2024 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Use this aggregated ClusterRole when you need cluster wide crossnamespace subscribe permissions for all resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossnamespace-subscriber
  labels:
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-eventing
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      duck.knative.dev/crossnamespace-subscribable: "true"
rules: [] # rules are automatically filled in by the controller manager.

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: channel-subscriber
  labels:
    duck.knative.dev/crossnamespace-subscribable: "true"
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-eventing
rules:
- apiGroups:
  - messaging.knative.dev
  resources:
  - channels
  verbs:
  - knsubscribe

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: broker-subscriber
  labels:
    duck.knative.dev/crossnamespace-subscribable: "true"
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-eventing
rules:
- apiGroups:
  - eventing.knative.dev
  resources:
  - brokers
  verbs:
  - knsubscribe
