apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: square
  labels:
    app: square
spec:
  replicas: 1
  template:
    metadata:
      name: square
      labels:
        app: square
    spec:
      containers:
      - image: spike/square:0.0.1
        name: main
        ports:
        - containerPort: 8080
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: square
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: square
